In [19]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
import pickle

In [20]:
df = pd.read_csv("data2.csv")
df_with_dummy = pd.get_dummies(df, columns=["propertyType"])
df_with_dummy.drop(columns=["Unnamed: 0"], inplace=True)

y = np.log(df_with_dummy.loc[:, "soldPrice"])
X = df_with_dummy.loc[:, "bednumber":]
X = X.loc[:, ~X.columns.isin(["latitude", "longitude"])]

In [22]:
X["nearest_hospital_distance"] = X["nearest_hospital_distance"] * 1000

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

print(f"R squrad: {model.score(X_test, y_test)}")
print(f"MSE: {mean_squared_error(predictions, y_test)}")

R squrad: 0.5012424840071016
MSE: 0.10513298886742027

\begin{align}
log(Price) = &\beta_0\ + \\
            &\beta_1Number\ of\  bathrooms \ + \\
            &\beta_2Old/New \ + \\
            &\beta_3Property Type \ + \\
            &\beta_4Latitude\ + \\
            &\beta_5Longitude
\end{align}

In [24]:
df

,Unnamed: 0,Unnamed: 0.1,soldPrice,bednumber,propertyType,duration_free_not_lease,isNew,latitude,longitude,nearest_hospital_distance
0,0,0,155000,2,Flat,0,0,51.286798,-2.820970,0.021107
1,1,1,253000,3,Semi-Detached,1,0,51.288002,-2.814496,0.014623
2,2,2,347500,4,Detached,1,0,51.287815,-2.813015,0.013142
3,3,3,320000,4,Detached,1,0,51.286798,-2.822261,0.022397
4,4,4,234000,2,Detached,1,0,51.287799,-2.810176,0.010303
5,5,5,219000,2,Terraced,1,0,51.287296,-2.815401,0.015527
6,6,6,343000,4,Detached,1,0,51.288177,-2.811358,0.011483
7,7,7,151500,2,Flat,0,0,51.285478,-2.816930,0.017065
8,8,8,580000,6,Terraced,1,0,51.287640,-2.821185,0.021309
9,9,9,230000,2,Semi-Detached,1,0,51.286836,-2.819365,0.019503
10,10,10,168750,3,Semi-Detached,1,0,51.287815,-2.813015,0.013142
11,11,11,220000,2,Detached,1,0,51.285849,-2.816408,0.016534
12,12,12,255000,3,Detached,1,0,51.288420,-2.814346,0.014471
13,13,13,375000,4,Detached,1,0,51.288097,-2.808690,0.008816
14,14,14,119000,2,Flat,0,0,51.285849,-2.816408,0.016534
15,15,15,260000,2,Detached,1,0,51.288177,-2.811358,0.011483
16,16,16,220000,2,Detached,1,0,51.287799,-2.810176,0.010303
17,17,17,449250,4,Semi-Detached,1,0,51.286425,-2.813880,0.014009
18,18,18,285000,3,Detached,1,0,51.286810,-2.817931,0.018070
19,19,19,120000,1,Flat,0,0,51.285478,-2.816930,0.017065
20,20,20,355000,4,Terraced,1,0,51.287640,-2.821185,0.021309
21,21,21,293500,4,Terraced,1,0,51.285625,-2.820261,0.020390
22,22,22,380000,4,Detached,1,0,51.288177,-2.811358,0.011483
23,23,23,210000,2,Semi-Detached,1,0,51.286539,-2.818069,0.018199
24,24,24,263000,4,Terraced,1,0,51.285407,-2.818020,0.018157
25,25,25,325000,4,Semi-Detached,1,0,51.285625,-2.820261,0.020390
26,26,26,165000,3,Semi-Detached,1,0,51.285372,-2.813962,0.014103
27,27,27,95000,1,Flat,0,0,51.286798,-2.820970,0.021107
28,28,28,360000,4,Detached,1,0,51.288097,-2.808690,0.008816
29,29,29,292500,4,Detached,1,0,51.287720,-2.812512,0.012637
...,...,...,...,...,...,...,...,...,...,...
22840,22840,22840,170000,3,Terraced,1,0,50.948746,-2.621043,0.005142
22841,22841,22841,235000,3,Detached,1,0,50.951363,-2.621006,0.005300
22842,22842,22842,165000,2,Semi-Detached,1,0,50.953071,-2.629514,0.000447
22843,22843,22843,200000,3,Semi-Detached,1,0,50.956286,-2.631964,0.003144
22844,22844,22844,132000,3,Terraced,1,0,50.947767,-2.635877,0.001986
22845,22845,22845,207500,3,Semi-Detached,1,0,50.945378,-2.654861,0.002770
22846,22846,22846,236000,3,Detached,1,0,50.943650,-2.651791,0.005911
22847,22847,22847,130000,2,Terraced,1,0,50.946095,-2.625634,0.003662
22848,22848,22848,154000,3,Semi-Detached,1,0,50.954210,-2.628419,0.000841
22849,22849,22849,79000,1,Flat,0,0,50.956789,-2.613462,0.002480
22850,22850,22850,197500,3,Semi-Detached,1,0,50.933860,-2.646474,0.008145
22851,22851,22851,180000,3,Semi-Detached,1,0,50.956335,-2.609213,0.002186
22852,22852,22852,155000,2,Terraced,1,0,50.954933,-2.663438,0.003291
22853,22853,22853,223000,4,Terraced,1,0,50.956248,-2.606222,0.002095
22854,22854,22854,198000,3,Semi-Detached,1,0,50.957103,-2.620399,0.005010
22855,22855,22855,253000,3,Detached,1,0,50.955206,-2.625656,0.003453
22856,22856,22856,160000,2,Detached,0,0,50.946814,-2.644063,0.006021
22857,22857,22857,258000,3,Semi-Detached,1,0,50.943769,-2.656276,0.001691
22858,22858,22858,256500,3,Detached,1,0,50.953585,-2.647289,0.008927
22859,22859,22859,147000,2,Semi-Detached,1,0,50.941482,-2.640545,0.004005
22860,22860,22860,105000,2,Semi-Detached,1,0,50.947895,-2.617046,0.002067
22861,22861,22861,177000,3,Semi-Detached,1,0,50.941113,-2.645578,0.008116
22862,22862,22862,171000,2,Semi-Detached,1,0,50.947177,-2.668908,0.003194
22863,22863,22863,142000,3,Terraced,1,0,50.957886,-2.615142,0.003165
22864,22864,22864,155000,2,Terraced,1,0,50.956612,-2.607067,0.001972
22865,22865,22865,187500,3,Semi-Detached,1,0,50.954022,-2.651181,0.006438
22866,22866,22866,215000,3,Semi-Detached,1,0,50.955616,-2.661910,0.004419
22867,22867,22867,133000,1,Terraced,1,0,50.949559,-2.667646,0.000929
22868,22868,22868,399950,5,Detached,1,0,50.926584,-2.664301,0.002765
22869,22869,22869,310000,4,Detached,1,0,50.950188,-2.635483,0.000568

In [18]:
X

,bednumber,duration_free_not_lease,isNew,propertyType_Detached,propertyType_Flat,propertyType_Semi-Detached,propertyType_Terraced
0,2,0,0,0,1,0,0
1,3,1,0,0,0,1,0
2,4,1,0,1,0,0,0
3,4,1,0,1,0,0,0
4,2,1,0,1,0,0,0
5,2,1,0,0,0,0,1
6,4,1,0,1,0,0,0
7,2,0,0,0,1,0,0
8,6,1,0,0,0,0,1
9,2,1,0,0,0,1,0
10,3,1,0,0,0,1,0
11,2,1,0,1,0,0,0
12,3,1,0,1,0,0,0
13,4,1,0,1,0,0,0
14,2,0,0,0,1,0,0
15,2,1,0,1,0,0,0
16,2,1,0,1,0,0,0
17,4,1,0,0,0,1,0
18,3,1,0,1,0,0,0
19,1,0,0,0,1,0,0
20,4,1,0,0,0,0,1
21,4,1,0,0,0,0,1
22,4,1,0,1,0,0,0
23,2,1,0,0,0,1,0
24,4,1,0,0,0,0,1
25,4,1,0,0,0,1,0
26,3,1,0,0,0,1,0
27,1,0,0,0,1,0,0
28,4,1,0,1,0,0,0
29,4,1,0,1,0,0,0
...,...,...,...,...,...,...,...
22840,3,1,0,0,0,0,1
22841,3,1,0,1,0,0,0
22842,2,1,0,0,0,1,0
22843,3,1,0,0,0,1,0
22844,3,1,0,0,0,0,1
22845,3,1,0,0,0,1,0
22846,3,1,0,1,0,0,0
22847,2,1,0,0,0,0,1
22848,3,1,0,0,0,1,0
22849,1,0,0,0,1,0,0
22850,3,1,0,0,0,1,0
22851,3,1,0,0,0,1,0
22852,2,1,0,0,0,0,1
22853,4,1,0,0,0,0,1
22854,3,1,0,0,0,1,0
22855,3,1,0,1,0,0,0
22856,2,0,0,1,0,0,0
22857,3,1,0,0,0,1,0
22858,3,1,0,1,0,0,0
22859,2,1,0,0,0,1,0
22860,2,1,0,0,0,1,0
22861,3,1,0,0,0,1,0
22862,2,1,0,0,0,1,0
22863,3,1,0,0,0,0,1
22864,2,1,0,0,0,0,1
22865,3,1,0,0,0,1,0
22866,3,1,0,0,0,1,0
22867,1,1,0,0,0,0,1
22868,5,1,0,1,0,0,0
22869,4,1,0,1,0,0,0

In [4]:
X["bednumber"] = X["bednumber"] ** 2

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()

model.fit(X_train, y_train)

predictions = model.predict(X_test)

print(f"R squrad: {model.score(X_test, y_test)}")
print(f"MSE: {mean_squared_error(predictions, y_test)}")

R squrad: 0.6233126294655015
MSE: 0.07940184932163534

In [4]:
def serialize(obj, path):
    """
    Pickle a Python object
    """
    with open(path, "wb") as pfile:
        pickle.dump(obj, pfile)

In [5]:
pkl_path = "./app/linear_regression.pkl"
serialize(model, pkl_path)

In [ ]:
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# import numpy as np
# import matplotlib.pyplot as plt

# scaler = StandardScaler()
# scaler.fit(X_train)
# X_train = scaler.transform(X_train)
# X_test = scaler.transform(X_test)

# model = RandomForestRegressor(n_jobs=-1)

# estimators = np.arange(10, 200, 10)
# scores = []
# for n in estimators:
#     model.set_params(n_estimators=n)
#     model.fit(X_train, y_train)
#     scores.append(model.score(X_test, y_test))
# plt.title("Effect of n_estimators")
# plt.xlabel("n_estimator")
# plt.ylabel("score")
# plt.plot(estimators, scores)

# scores